require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ChatWithMe' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  target 'ChatWithMeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ChatWithMe-tvOS' do
  # Pods for ChatWithMe-tvOS

  target 'ChatWithMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
